### ISSUE TITLE
home/landing page needs to be made

### ISSUE THREAD

**Issue by itsaboy** [itsaboy/local-planting-planner#22]
The page that shows when the user first visits the site/ no zip code has been searched yet. This can either be a new index.html and we move what exists now to a results page or we can make a SPA and everything dynamically renders onto the index.html page

**Comment by itsaboy** [comment]
Needs a layout, styling, images, description of hardiness zones, etc etc

**Comment by Katherine-V** [comment]
So this issue would be 
index page- html
So mind if I make another issue for
index page- JS functionality

**Comment by itsaboy** [comment]
yea I would split up and let whoever wants to assign themselves to it, once its split up just delete this one
