### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by itsaboy** [itsaboy/local-planting-planner#3]
Pages need to be styles as close as possible to David's specifications

**Comment by itsaboy** [comment]
Note: all the CSS styles in the style.css file were just for the wireframe. They can/should be removed by whoever wants to do any CSS stuff.

**Comment by itsaboy** [comment]
styling for both pages

**Comment by Katherine-V** [comment]
Whomever is working on this, I'm curious about color themes and so on to be shared by both of the pages. As far as I know, we're settled on a font. But has anyone sketched up an update to that first wireframe? I'd be interested, if that seems useful to get drawn and the layout details agreed on.

**Comment by itsaboy** [comment]
Closing this because it is so general and opening a new issue about the color palette
