### ISSUE TITLE
index page - javascript function

### ISSUE THREAD

**Issue by Katherine-V** [itsaboy/local-planting-planner#35]
I believe the zip code search function is already established.
I added this issue in case we want more interactive features, like a little dropdown menu.
Feel free to close this issue if we'd prefer to make the first page streamlined.

**Comment by itsaboy** [comment]
local storage capability is already coded into the JS but its not actually used anywhere. A dropdown for previous searched and saved zip codes would be the easiest thing to do, and it makes sense to have it on both the homepage and the results page.
